version: '3.7'
services:
        flask-app:
                build: ./flask-app
                ports:
                        - target: 5000
                          published: 5000
                          protocol: tcp
                depends_on:
                       - mysql
                environment:
                       DATABASE_URI: ${DATABASE_URI}
        mysql:
                build: ./db
                ports:
                        - target: 3306
                          published: 3306
                          protocol: tcp
                environment: 
                        - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}

        nginx:
                image: nginx:latest
                ports:
                        - target: 80
                          published: 80
                          protocol: tcp
                volumes:
                        - type: bind
                          source: ./nginx/nginx.conf
                          target: /etc/nginx/nginx.conf
                depends_on:
                        - flask-app
                               
                
        
